---
apiVersion: v1
kind: Service
metadata:
  name: minyx-resume
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: minyx-resume
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer